### ISSUE TITLE
Sent 1 GRLC to an address, but all GRLC missing

### ISSUE THREAD

**Issue by robjadams** [xSke/garlium#11]
Had ~16 GRLC in one address. I sent 1 GRLC to someone using their provided address. That transaction was successful, and shows up in my history.

Immediately after that, I see that I have 0 GRLC in my original address. Looking at the blockchain explorer, apparently the remaining ~15 GRLC or so was sent to another address that I did not input. This second transaction doesn't show up in Garlium. What happened? This is super concerning. 

My Galrium balance at the bottom still displays my correct total balance, but my address shows 0. Why?

I can provide pictures and other information. Thanks.

**Comment by xSke** [comment]
That's a change address. This is because of how the Bitcoin protocol works. See: https://en.bitcoin.it/wiki/Coin_analogy

**Comment by robjadams** [comment]
Damn, I feel dumb. Thanks so much for the answer, I was getting pretty bummed. I've seen some others express concern about this and I'll be sure to inform other inexperienced folk like me.

And thanks for doing all this work and still being so communicative! It does not go overlooked.
