### ISSUE TITLE
Error "Unknown address type" after reinstall

### ISSUE THREAD

**Issue by nathanjosiah** [xSke/garlium#22]
I had the testnet client installed. I uninstalled it and installed the new current version and I am now getting this error when I attempt to open it.

![image](https://user-images.githubusercontent.com/665104/35455173-ce951f06-0285-11e8-83a8-8c997c6774dc.png)

**Comment by Tri125** [comment]
Does your address begin with G? Mainet address start with G (not m). You will have to create a new address for mainet.

**Comment by nathanjosiah** [comment]
@Tri125 I would assume not but as I said it won't even open for me to do anything. I click to open the program and the first and only thing I see is the error above and then it all closes. No tray icon, no background window, no task.

**Comment by Tri125** [comment]
If you want to confirm whether or not you had a testnet address and you don't know your public address or private key, the faster way to confirm would be to reinstall the testnet client and import the wallet.

**Comment by nathanjosiah** [comment]
@Tri125 I had a testnet address but I uninstalled the testnet client and installed the main net client.

**Comment by Tri125** [comment]
Alright, then feel free to delete your testnet wallet. It can't be used or imported for the mainnet.

**Comment by nathanjosiah** [comment]
@Tri125 Great! That did it. Thank you!
