### ISSUE TITLE
Garlium very rarely able to launch wallet

### ISSUE THREAD

**Issue by clubby789** [xSke/garlium#40]
I am using the latest version of Garlium, built from source. However, whenever I enter my password and try to launch, Garlium crashes with a 'Garlium.exe has stopped working' message appearing twice and the program closing. Occasionally it does launch properly. I never had this problem on the latest 'Release' build

**Comment by clubby789** [comment]
Problem solved by deleting %AppData%/Garlium/blockchain_headers

**Comment by clubby789** [comment]
Problem keeps reoccurring, sometimes doesn’t work even after deleting blockchain_headers

**Comment by webworker01** [comment]
Garlium crashes constantly on Windows 10. Can't even load up balances. I've tried deleting the blockchain_headers and also completely deleting the %appdata% folder.

**Comment by mlallan1307** [comment]
Same here. I don't get any error. Just enter password, electrum window pops up but no transactions shown, then just closes itself. Deleting blockchain_headers doesn't solve it. Just have to reopen it about a dozen or so times until it finally works. Hope this is fixed soon

**Comment by octylFractal** [comment]
I'm seeing this on Ubuntu as well, I haven't gotten it to work after multiple launches, it just freezes on the opening screen after I put in my password and hit Next.

In case it helps, here's where it crashes when I do Ctrl-C:
```
Traceback (most recent call last):
  File "/home/octy/.virtualenvs/garlium/lib/python3.6/site-packages/Garlium-3.0.5-py3.6.egg/electrum_ltc_gui/qt/installwizard.py", line 232, in run_and_get_wallet
    self.storage.decrypt(password)
  File "/home/octy/.virtualenvs/garlium/lib/python3.6/site-packages/Garlium-3.0.5-py3.6.egg/electrum_ltc/storage.py", line 125, in decrypt
    s = zlib.decompress(ec_key.decrypt_message(self.raw)) if self.raw else None
  File "/home/octy/.virtualenvs/garlium/lib/python3.6/site-packages/Garlium-3.0.5-py3.6.egg/electrum_ltc/bitcoin.py", line 836, in decrypt_message
    return aes_decrypt_with_iv(key_e, iv, ciphertext)
  File "/home/octy/.virtualenvs/garlium/lib/python3.6/site-packages/Garlium-3.0.5-py3.6.egg/electrum_ltc/bitcoin.py", line 169, in aes_decrypt_with_iv
    data = aes.feed(data) + aes.feed()  # empty aes.feed() flushes buffer
  File "/home/octy/.virtualenvs/garlium/lib/python3.6/site-packages/pyaes-1.6.1-py3.6.egg/pyaes/blockfeeder.py", line 181, in feed
    self._buffer = self._buffer[can_consume:]
```

**Comment by ghost** [comment]
Same problem here on Windows 10 with latest Garlium. Deleting `blockchain_headers` or a complete re-install doesn't make much difference. Eventually the wallet opens and syncs, but it's rather intermittent. Sometimes it works at the first try, sometimes I have to try 10+ times.

Here's one of many log entries from Windows' Event Viewer

> Faulting application name: Garlium.exe, version: 0.0.0.0, time stamp: 0x597f4ad5
> Faulting module name: Qt5Gui.dll, version: 5.9.3.0, time stamp: 0x5a0c7fca
> Exception code: 0xc0000005
> Fault offset: 0x00087981
> Faulting process ID: 0x1e7c
> Faulting application start time: 0x01d3aabd0f930e7d
> Faulting application path: C:\Program Files (x86)\Garlium\Garlium.exe
> Faulting module path: C:\Program Files (x86)\Garlium\Qt5Gui.dll
> Report ID: 18f0ca8e-a246-472b-bd96-9e1be0ec8e24
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by joelschwabe** [comment]
I'm having the same issue

> Faulting application name: Garlium.exe, version: 0.0.0.0, time stamp: 0x597f4ad5
Faulting module name: Qt5Gui.dll, version: 5.9.3.0, time stamp: 0x5a0c7fca
Exception code: 0xc0000005
Fault offset: 0x000d5a60
Faulting process id: 0x295c
Faulting application start time: 0x01d3ac44d9bb4695
Faulting application path: C:\Program Files (x86)\Garlium\Garlium.exe
Faulting module path: C:\Program Files (x86)\Garlium\Qt5Gui.dll
Report Id: 00d2b9af-233d-4459-8649-07555cbe4f39
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mlallan1307** [comment]
To try and fix this on my end I played around with several things and now it doesn't seem to be happening anymore. Not sure which of these made a difference (or any of them really). If it happens again I'll post again but I figured this may help someone:

1. Tools>preferences>Appearance>Online_Block_Explorer   Select "Bakery"
2. Tools>network>server   Disable auto selection and select "garlium.garlicpool.org"
3. I had over 2500 Transactions from mining. I consolidated them by:
    - View>show_coins
    - Select 200 transactions, right click "spend"
    - Enter one of your addresses in the "Pay to" box
    - Select Max
    - Preview, sign, broadcast
    - Repeat above until coins are consolidated
4. If none of the above worked. In the Roaming>Garlium directory, Delete everything except the wallets directory. Then reinstall Garlium

**Comment by Kyouten** [comment]
Having the same issue. No commits have been made in over a month, considering Garlium a dead wallet at this point.
