### ISSUE TITLE
Not connecting to network

### ISSUE THREAD

**Issue by xenonnsmb** [xSke/garlium#5]
I'm running Garlium from source on macOS, and it won't connect to any servers. I get this in the console:

`[SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
[84.245.14.110] failed to connect [Errno 61] Connection refused
[SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
[172.93.54.31] SSL error retrieving SSL certificate: [SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
[SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
[mhamburger.net] SSL error retrieving SSL certificate: [SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
`

Is this an issue with Garlium, or did I just not install it correctly?

**Comment by xSke** [comment]
From a quick Google, this looks like it's caused by outdated versions of SSL libraries. Is your system updated?

**Comment by xenonnsmb** [comment]
I fixed it. The issue was that my python3 and pip3 were symlinked to python3.5, not python3.6. I fixed this by putting this in my .bash_profile:
```
alias python3=/usr/local/bin/python3.6
alias pip3=/usr/local/bin/pip3.6
```
