### ISSUE TITLE
Price Checking Still uses Litecoin Price

### ISSUE THREAD

**Issue by JonnoFTW** [xSke/garlium#6]
When you set the Fiat currency under Tools -> Preferences -> Fiat Currency and a source, the balance shown will not be correct.

![Screenshot](https://puu.sh/z7uyM/d943d1c9e4.png)

**Comment by nateevans** [comment]
@xSke how about https://tradesatoshi.com/Exchange?market=GRLC_BTC ? Not sure if that exchange is sketchy or not to be considered real :) haven't used them before

**Comment by clubby789** [comment]
I built the latest version and it now has proper support for GRLC exchanges

**Comment by xSke** [comment]
Yeah, this was fixed in 4cd15251. Closing.
