### ISSUE TITLE
Can't Send Garlic

### ISSUE THREAD

**Issue by msfoste** [xSke/garlium#9]
I'm using the windows client 3.0.5 and when I try to send any coins the "signing transaction" window pops up and the coins won't go through. I've tried tried increasing the fee and tried using it on another computer but the problem persist, both were Windows 7 AMD systems if that has to do with anything. When exiting out of the transaction window after waiting, the client slows to a crawl and needs to be restarted. I've tried deleting the appdata folder (excluding the wallet). If it helps any, the wallet is imported. Creating a new wallet and importing the private key doesn't change a thing either.

**Comment by xSke** [comment]
Do you have a lot of small incoming transactions in your wallet (eg. from mining)? If so, there might be far too many inputs to your transaction. See the website for information on how to consolidate those into smaller inputs.

**Comment by msfoste** [comment]
That fixed it, thanks man.
